-- CREATE TABLE users (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     email TEXT UNIQUE NOT NULL,
--     username TEXT UNIQUE NOT NULL,
--     password TEXT NOT NULL
-- );

-- CREATE TABLE posts (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     user_id INTEGER NOT NULL,
--     category TEXT,
--     title TEXT NOT NULL,
--     content TEXT NOT NULL,
--     created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
--     FOREIGN KEY (user_id) REFERENCES users(id)
-- );

-- CREATE TABLE comments (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     post_id INTEGER NOT NULL,
--     user_id INTEGER NOT NULL,
--     content TEXT NOT NULL,
--     created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
--     FOREIGN KEY (post_id) REFERENCES posts(id),
--     FOREIGN KEY (user_id) REFERENCES users(id)
-- );

-- CREATE TABLE categories (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     name TEXT UNIQUE NOT NULL
-- );

-- CREATE TABLE post_categories (
--     post_id INTEGER,
--     category_id INTEGER,
--     FOREIGN KEY (post_id) REFERENCES posts(id),
--     FOREIGN KEY (category_id) REFERENCES categories(id),
--     PRIMARY KEY (post_id, category_id)
-- );

-- CREATE TABLE likes (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     post_id INTEGER,
--     comment_id INTEGER,
--     user_id INTEGER NOT NULL,
--     type INTEGER NOT NULL,  -- 1 for like, -1 for dislike
--     created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
--     FOREIGN KEY (post_id) REFERENCES posts(id),
--     FOREIGN KEY (comment_id) REFERENCES comments(id),
--     FOREIGN KEY (user_id) REFERENCES users(id)
-- );
